### ISSUE TITLE
Desenho do Circuito

### ISSUE THREAD

**Issue by AndrewLaganaro** [matheusbach/ESP32-Bitcoin-Monitor#1]
Se possível, disponibiliza um desenho do circuito. Seria muito bacana pra reproduzir

Apesar de já ter foto, um desenho deixaria mais específico os pinos e tiraria quaisquer dúvidas sobre como montar :) 

Fica a sugestão. Abraços!

**Comment by matheusbach** [comment]
Se você aproximar a imagem pode ver todos os nomes dos pinos e ver pela legenda. De qualquer forma fiz essa ilustraçao.

Não consegui fazer em ferramentas como o thinkercad por que não tem os componentes então fiz no gimp mesmo

Espero que ajude

![esquema](https://raw.githubusercontent.com/matheusbach/ESP32-Bitcoin-Monitor/main/esquema.png)

**Comment by AndrewLaganaro** [comment]
Valeu haushaj

Na verdade eu não tinha reparado a legenda. Pior que tem mesmo! Mesmo assim vlw pelo desenho. Se eu conseguir faço um pra vc postar aqui ☺️

**Comment by AndrewLaganaro** [comment]
Fiz um pull request com o desenho do circuito :D dá uma olhada lá
